<?php

namespace Database\Seeders;

use App\Enums\JobTypesEnum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class jobseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('job_posting')->insert([
            [
                'title' => 'Laravel Developer',
                'user_id' => 1,
                'description' => '<p>We are looking for a skilled <strong>Laravel Developer</strong> to build and maintain web applications. The candidate should have experience working with modern web technologies.</p>',
                'requirements' => '<ul><li>Proficiency in <strong>PHP, Laravel, MySQL</strong></li><li>Experience with <strong>REST APIs</strong> and authentication mechanisms</li><li>Familiarity with version control (Git)</li><li>Basic understanding of frontend technologies like <strong>Vue.js</strong> or <strong>React</strong></li><li>Strong problem-solving skills and attention to detail</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and interpersonal skills</li><li>Ability to adapt to changing project requirements and priorities</li><li>Strong understanding of software development life cycles</li><li>Experience with Agile development methodologies</li><li>Knowledge of security best practices and coding standards</li></ul>',
                'salary_range' => '80,000 - 120,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Senior Laravel Engineer',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>Senior Laravel Engineer</strong> with expertise in building <em>scalable applications</em> and optimizing backend performance.</p>',
                'requirements' => '<ul><li>5+ years of experience with <strong>Laravel</strong> and backend development</li><li>Strong knowledge of <strong>database optimization</strong> and caching techniques</li><li>Experience with <strong>AWS</strong> services and CI/CD pipelines</li><li>Proficiency in <strong>Vue.js</strong> or <strong>React</strong> is a plus</li><li>Strong understanding of software architecture and design patterns</li><li>Experience with containerization using Docker</li><li>Knowledge of serverless computing and cloud-native applications</li><li>Strong problem-solving skills and ability to debug complex issues</li><li>Excellent leadership and mentoring skills</li><li>Ability to communicate technical ideas to non-technical stakeholders</li></ul>',
                'salary_range' => '150,000 - 200,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Backend Developer (Laravel)',
                'user_id' => 1,
                'description' => '<p>We are seeking a <strong>Backend Developer</strong> with experience in building robust APIs and optimizing database performance.</p>',
                'requirements' => '<ul><li>Strong experience in <strong>Laravel and API development</strong></li><li>Knowledge of <strong>MongoDB</strong> and NoSQL databases is a plus</li><li>Familiarity with <strong>unit testing</strong> and debugging</li><li>Understanding of security best practices</li><li>Experience with message queues and job scheduling</li><li>Knowledge of caching mechanisms and performance optimization</li><li>Strong problem-solving skills and attention to detail</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and interpersonal skills</li></ul>',
                'salary_range' => '100,000 - 140,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::HYBRID,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Full Stack Developer (Laravel & Vue.js)',
                'user_id' => 1,
                'description' => '<p>We are looking for a skilled <strong>Full Stack Developer</strong> with experience in building scalable web applications using Laravel and Vue.js.</p>',
                'requirements' => '<ul><li>Strong experience in <strong>Laravel and Vue.js</strong></li><li>Knowledge of <strong>REST APIs</strong> and authentication mechanisms</li><li>Familiarity with version control (Git)</li><li>Basic understanding of frontend technologies like <strong>HTML, CSS, and JavaScript</strong></li><li>Strong problem-solving skills and attention to detail</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and interpersonal skills</li><li>Ability to adapt to changing project requirements and priorities</li><li>Strong understanding of software development life cycles</li><li>Experience with Agile development methodologies</li><li>Knowledge of security best practices and coding standards</li></ul>',
                'salary_range' => '120,000 - 180,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DevOps Engineer (AWS & Docker)',
                'user_id' => 1,
                'description' => '<p>We are seeking a skilled <strong>DevOps Engineer</strong> with experience in building and maintaining scalable infrastructure using AWS and Docker.</p>',
                'requirements' => '<ul><li>Strong experience in <strong>AWS and Docker</strong></li><li>Knowledge of <strong>CI/CD pipelines</strong> and automation tools</li><li>Familiarity with <strong>containerization</strong> and orchestration</li><li>Basic understanding of <strong>security best practices</strong> and compliance</li><li>Strong problem-solving skills and attention to detail</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and interpersonal skills</li><li>Ability to adapt to changing project requirements and priorities</li><li>Strong understanding of software development life cycles</li><li>Experience with Agile development methodologies</li><li>Knowledge of security best practices and coding standards</li></ul>',
                'salary_range' => '150,000 - 220,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Quality Assurance (QA) Engineer',
                'user_id' => 1,
                'description' => '<p>We are looking for a skilled <strong>QA Engineer</strong> with experience in building and maintaining automated testing frameworks.</p>',
                'requirements' => '<ul><li>Strong experience in <strong>automated testing</strong> and QA methodologies</li><li>Knowledge of <strong>testing frameworks</strong> like Selenium or Appium</li><li>Familiarity with <strong>Agile development methodologies</strong> and version control (Git)</li><li>Basic understanding of <strong>software development life cycles</strong> and coding standards</li><li>Strong problem-solving skills and attention to detail</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and interpersonal skills</li><li>Ability to adapt to changing project requirements and priorities</li><li>Strong understanding of software development life cycles</li><li>Experience with Agile development methodologies</li><li>Knowledge of security best practices and coding standards</li></ul>',
                'salary_range' => '80,000 - 120,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::HYBRID,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Frontend Developer (React.js)',
                'user_id' => 1,
                'description' => '<p>We are looking for a skilled <strong>Frontend Developer</strong> with expertise in React.js to build and maintain user interfaces for web applications.</p>',
                'requirements' => '<ul><li>Proficiency in <strong>React.js, JavaScript, HTML, and CSS</strong></li><li>Experience with state management libraries like <strong>Redux</strong></li><li>Familiarity with REST APIs and modern frontend build tools</li><li>Strong problem-solving skills and attention to detail</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and interpersonal skills</li></ul>',
                'salary_range' => '90,000 - 130,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mobile App Developer (Flutter)',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>Mobile App Developer</strong> with experience in building cross-platform applications using Flutter.</p>',
                'requirements' => 'Proficiency in Flutter and Dart, Experience with REST APIs and state management, Familiarity with version control (Git), Strong problem-solving skills and attention to detail, Ability to work collaboratively in a team environment, Excellent communication and interpersonal skills',
                'salary_range' => '100,000 - 150,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'UI/UX Designer',
                'user_id' => 1,
                'description' => '<p>We are seeking a creative <strong>UI/UX Designer</strong> to design intuitive and user-friendly interfaces for web and mobile applications.</p>',
                'requirements' => 'Proficiency in design tools like Figma, Adobe XD, or Sketch, Experience with user research and wireframing, Strong understanding of design principles and accessibility, Ability to collaborate with developers and product managers, Excellent communication and interpersonal skills',
                'salary_range' => '70,000 - 110,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Data Scientist',
                'user_id' => 1,
                'description' => '<p>We are looking for a <strong>Data Scientist</strong> with expertise in machine learning, data analysis, and predictive modeling.</p>',
                'requirements' => 'Proficiency in Python, R, or SQL, Experience with machine learning frameworks like TensorFlow or PyTorch, Strong understanding of statistical analysis and data visualization, Ability to work with large datasets and cloud platforms, Excellent problem-solving and communication skills',
                'salary_range' => '150,000 - 200,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cloud Engineer (Azure)',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>Cloud Engineer</strong> with expertise in Microsoft Azure to design and manage cloud infrastructure.</p>',
                'requirements' => 'Proficiency in Microsoft Azure services, Experience with infrastructure as code (IaC) tools like Terraform, Strong understanding of networking and security in the cloud, Ability to optimize cloud costs and performance, Excellent problem-solving and communication skills',
                'salary_range' => '120,000 - 180,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Product Manager',
                'user_id' => 1,
                'description' => '<p>We are seeking a <strong>Product Manager</strong> to lead the development and launch of new products and features.</p>',
                'requirements' => '<p>Experience in product management and Agile methodologies, Strong understanding of user needs and market trends, Ability to collaborate with cross-functional teams, Excellent communication and leadership skills, Strong problem-solving and decision-making abilities</p>',
                'salary_range' => '150,000 - 220,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Technical Writer',
                'user_id' => 1,
                'description' => '<p>We are looking for a <strong>Technical Writer</strong> to create clear and concise documentation for our software products.</p>',
                'requirements' => '<ul><li>Experience in technical writing and documentation</li><li>Strong understanding of software development processes</li><li>Ability to translate complex technical concepts into user-friendly content</li><li>Excellent communication and writing skills</li></ul>',
                'salary_range' => '60,000 - 90,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::HYBRID,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'System Administrator',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>System Administrator</strong> to manage and maintain our IT infrastructure.</p>',
                'requirements' => '<ul><li>Experience with Linux/Windows server administration</li><li>Knowledge of networking and security best practices</li><li>Ability to troubleshoot and resolve technical issues</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '80,000 - 120,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blockchain Developer',
                'user_id' => 1,
                'description' => '<p>We are seeking a <strong>Blockchain Developer</strong> with experience in building decentralized applications (dApps).</p>',
                'requirements' => '<ul><li>Proficiency in <strong>Solidity, Ethereum, or Hyperledger</strong></li><li>Experience with smart contracts and blockchain protocols</li><li>Strong understanding of cryptography and security</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '200,000 - 300,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AI/ML Engineer',
                'user_id' => 1,
                'description' => '<p>We are looking for an <strong>AI/ML Engineer</strong> to develop and deploy machine learning models.</p>',
                'requirements' => '<ul><li>Proficiency in <strong>Python, TensorFlow, or PyTorch</strong></li><li>Experience with data preprocessing and model training</li><li>Strong understanding of machine learning algorithms</li><li>Ability to work with large datasets and cloud platforms</li><li>Excellent problem-solving and communication skills</li></ul>',
                'salary_range' => '180,000 - 250,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cybersecurity Analyst',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>Cybersecurity Analyst</strong> to protect our systems and data from cyber threats.</p>',
                'requirements' => '<ul><li>Experience with security tools and techniques</li><li>Knowledge of network security and vulnerability assessment</li><li>Ability to respond to and mitigate security incidents</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '100,000 - 150,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Game Developer (Unity)',
                'user_id' => 1,
                'description' => '<p>We are seeking a <strong>Game Developer</strong> with experience in Unity to create engaging and interactive games.</p>',
                'requirements' => '<ul><li>Proficiency in <strong>Unity and C#</strong></li><li>Experience with game physics and animation</li><li>Strong understanding of game design principles</li><li>Ability to work collaboratively in a team environment</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '120,000 - 180,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Database Administrator (DBA)',
                'user_id' => 1,
                'description' => '<p>We are looking for a <strong>Database Administrator</strong> to manage and optimize our database systems.</p>',
                'requirements' => '<ul><li>Experience with <strong>MySQL, PostgreSQL, or MongoDB</strong></li><li>Knowledge of database performance tuning and backup strategies</li><li>Ability to troubleshoot and resolve database issues</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '90,000 - 140,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Scrum Master',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>Scrum Master</strong> to facilitate Agile processes and ensure project success.</p>',
                'requirements' => '<ul><li>Experience in Agile methodologies and Scrum practices</li><li>Ability to coach and mentor development teams</li><li>Strong understanding of project management tools</li><li>Excellent communication and leadership skills</li></ul>',
                'salary_range' => '100,000 - 150,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Business Analyst',
                'user_id' => 1,
                'description' => '<p>We are seeking a <strong>Business Analyst</strong> to analyze business processes and recommend solutions.</p>',
                'requirements' => '<ul><li>Experience in business analysis and requirements gathering</li><li>Strong understanding of business process modeling</li><li>Ability to collaborate with stakeholders and development teams</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '80,000 - 120,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Content Writer',
                'user_id' => 1,
                'description' => '<p>We are looking for a <strong>Content Writer</strong> to create engaging and informative content for our website and marketing materials.</p>',
                'requirements' => '<ul><li>Experience in content writing and SEO</li><li>Strong understanding of grammar and style</li><li>Ability to research and write on technical topics</li><li>Excellent communication and writing skills</li></ul>',
                'salary_range' => '50,000 - 80,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Network Engineer',
                'user_id' => 1,
                'description' => '<p>We are hiring a <strong>Network Engineer</strong> to design and maintain our network infrastructure.</p>',
                'requirements' => '<ul><li>Experience with network protocols and hardware</li><li>Knowledge of network security and troubleshooting</li><li>Ability to optimize network performance</li><li>Excellent communication and problem-solving skills</li></ul>',
                'salary_range' => '90,000 - 130,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Digital Marketing Specialist',
                'user_id' => 1,
                'description' => '<p>We are seeking a <strong>Digital Marketing Specialist</strong> to manage our online presence and marketing campaigns.</p>',
                'requirements' => '<ul><li>Experience with SEO, SEM, and social media marketing</li><li>Strong understanding of analytics and reporting tools</li><li>Ability to create and execute marketing strategies</li><li>Excellent communication and writing skills</li></ul>',
                'salary_range' => '70,000 - 110,000 PKR',
                'location' => 'Islamabad, Pakistan',
                'job_type' => JobTypesEnum::HYBRID,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'IT Support Specialist',
                'user_id' => 1,
                'description' => '<p>We are looking for an <strong>IT Support Specialist</strong> to provide technical support to our employees.</p>',
                'requirements' => '<ul><li>Experience with troubleshooting hardware and software issues</li><li>Knowledge of operating systems and networking</li><li>Ability to provide excellent customer service</li><li>Excellent communication and problem-solving skills</li> </ul>',
                'salary_range' => '50,000 - 80,000 PKR',
                'location' => 'Karachi, Pakistan',
                'job_type' => JobTypesEnum::FULL_TIME,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ERP Consultant',
                'user_id' => 1,
                'description' => '<p>We are hiring an <strong>ERP Consultant</strong> to implement and manage ERP systems for our clients.</p>',
                'requirements' => '<ul><li>Experience with ERP systems like <strong>SAP or Oracle</strong></li><li>Strong understanding of business processes and workflows</li><li>Ability to customize and confgure ERP solutions</li><li>Excellent communication and problem-solving skills</l</ul>',
                'salary_range' => '120,000 - 180,000 PKR',
                'location' => 'Lahore, Pakistan',
                'job_type' => JobTypesEnum::REMOTE,
                'status' => 'open',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
