services:
  - type: web
    name: laravel-app
    runtime: php
    buildCommand: |
      curl -s https://getcomposer.org/installer | php
      php composer.phar install --optimize-autoloader --no-dev
      php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:Wy+R8DCUGBfsp3o7uMZdVUAY3qEaNn6M7g5DGKsn82M=
      # - key: DB_CONNECTION
      #   value: mysql
      # - key: DB_HOST
      #   value: your_database_host
      # - key: DB_PORT
      #   value: 3306
      # - key: DB_DATABASE
      #   value: your_database_name
      # - key: DB_USERNAME
      #   value: your_database_user
      # - key: DB_PASSWORD
      #   value: your_database_password